marcosimbuerger_monitoringsatellite_get:
  path: /monitoring-satellite/v1/get
  defaults:
    _controller: MarcoSimbuerger\MonitoringSatelliteBundle\Controller\MonitoringSatelliteController::get
  methods:
    - GET
